#!/usr/bin/env ruby
# frozen_string_literal: true

require 'thor'

# The rifter CLI
class CLI < Thor
  desc 'launch [discord_token] [discord_client_id]', 'Launch rifter'
  def launch(token, id)
    require 'rifter'
    Rifter.launch(token, id)
  end
end

CLI.start(ARGV)
